# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:latest
stages:
- test
before_script:
- yarn install --frozen-lockfile
test:
  stage: test
  script:
  - yarn lint
  - yarn test
cache:
  paths:
  - node_modules/
  - ".yarn"
include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
